--CREATE TABLE EATS AS SELECT * FROM CAFE;
--SELECT * FROM EATS;
--
--CREATE TABLE EATS_MENU AS SELECT * FROM MENU;
--SELECT * FROM EATS_MENU;

-- 11번째 빠나쁘레쏘 '경기도 고양시' 031-123-4567

INSERT INTO EATS 
		VALUES (11, '빠나쁘레쏘', '경기도 고양시', '031-123-4567');		
COMMIT; -- INSERT UPDATE DELETE 추가 수정 삭제 한 기록 저장하기

-- 12번째 로맨틱블루 부산 해운대구 051-987-6543; 추가 후 저장
INSERT INTO EATS
		VALUES (12, '로맨틱블루', '부산 해운대구', '051-987-6543');
COMMIT;

-- 13
INSERT INTO EATS
		VALUES (13, '티하우스', '인천 남동구', '032-345-6789');

-- 14
INSERT INTO EATS
		VALUES (14, '라떼아트', '경기도 성남시', '031-654-3210');

-- 15
INSERT INTO EATS
		VALUES (15, '커피클럽', '대구 중구', '053-222-1111');
	
SELECT * FROM EATS;

ROLLBACK; -- DBEAVER 는 자동으로 COMMIT 하기 때문에 13 14 15 ROLLBACK이 안됨

DELETE FROM EATS WHERE CAFE_ID = 13;
DELETE FROM EATS WHERE CAFE_ID = 14;
DELETE FROM EATS WHERE CAFE_ID = 15;

--2번 방법을 이용해서 선택적으로 데이터 추가
---- 주의 ) NOT NULL은 선택적으로 작성 불가, 필수로 작성해야 하는 컬럼
--16 '브루윙랩' '대전 서구' '042-333-4444'
--- PRIMARY KEY -> 고유의 숫자값을 가지는 키 / 가입한 명단 순서 NULL
--- 트리거 시퀸스 -> ORACLE PRIMARY KEY는 자동으로 번호를 측정해주는 동작을 설정해줘야 함
INSERT INTO EATS (CAFE_ID, CAFE_NAME) VALUES (15, '빈포레스트');
SELECT * FROM EATS;

-- 빈 포레스라는 CAFE_NAME을 찾아서 삭제
DELETE FROM EATS WHERE CAFE_NAME = '빈포레스트';
SELECT * FROM EATS;

-- INSERT INTO EATS(CAFE_ID, CAFE_NAME, LOCATION, CONATCT_NUMBER)
-- VALUES(16 ~ 18)

-- 16
INSERT INTO EATS VALUES (16, '브루윙랩', '대전 서구', '042-333-4444');
	
-- 17
INSERT INTO EATS VALUES (17, '스윗빈즈', '광주 북구', '062-567-8901');
	
-- 18
INSERT INTO EATS VALUES (18, '카페 블랙', '울산 남구', '052-444-5555');
	
DELETE
FROM EATS
WHERE CAFE_ID = 16
AND CAFE_NAME = '스윗빈즈';

SELECT * FROM EATS;

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (19, '비바라떼', '전주시 덕진구', '063-111-2222');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (20, '바닐라하우스', '경기도 안양시', '031-987-1234');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (21, '카페 베르디', '서울 은평구', '010-2345-6780');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (22, '샌드커피', '경상남도 창원시', '055-765-4321');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (23, '헤이조이', '제주특별자치도 제주시', '064-987-6543');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (24, '스마일빈즈', '강원도 춘천시', '033-654-7890');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (25, '모닝커피', '충청북도 청주시', '043-876-5432');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (26, '빈하우스', '전라남도 목포시', '061-654-1234');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (27, '핸드드립존', '경기도 수원시', '031-765-8765');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (28, '어반커피', '서울 서대문구', '010-5432-9876');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (29, '테라스카페', '서울 동작구', '010-9876-1234');

INSERT INTO EATS (CAFE_ID, CAFE_NAME, LOCATION, CONTACT_NUMBER)
VALUES (30, '그린티라떼', '서울 송파구', '010-1234-5678');

-- DEPARTMENT 테이블에서 DEPT_ID 가 'D9'인 부서 정보 조회
SELECT * FROM DEPARTMENT
WHERE DEPT_ID = 'D9'; -- 총무부

-- DEPARTMENT 테이블에서 DEPT_ID 가 'D9'인 행의 DEPT_TITLE 을 전략기획팀으로 수정

UPDATE DEPARTMENT
SET DEPT_TITLE = '전략기회팀'
WHERE DEPT_ID = 'D9';

SELECT * FROM DEPARTMENT
WHERE DEPT_ID = 'D9'; -- 전략기획팀

SELECT * FROM EATS;
-- 로맨틱블루 라는 카페의 전화번호를 010-0000-1111로 변경
UPDATE EATS
SET CONTACT_NUMBER = '010-0000-1111'
WHERE CAFE_NAME = '로맨틱블루';

SELECT * FROM EATS_MENU;
-- EATS_MENU 테이블에서 MENU_NAME = 화이트 모카 인 메뉴의 가격을 6000원으로 업데이트
---- 메뉴 이름은 정확히 화이트 모카 만

UPDATE EATS_MENU 
SET PRICE = 6000
WHERE MENU_NAME = '화이트모카';
SELECT * FROM EATS_MENU;

UPDATE EATS_MENU 
SET DESCRIPTION = '홍차와 우유가 어우러진 진한 맛의 밀크티'
WHERE MENU_NAME = '밀크티';

UPDATE EATS_MENU 
SET PRICE = PRICE * 1.1
WHERE PRICE <= 5000;

-- 그린빈 카페 서울시 종로구 010-2345-6789 에서 경기도 안양시 주소 변경 전화번호 제거
-- 제거 = NULL 사용
UPDATE EATS
SET LOCATION = '경기도 안양시', CONTACT_NUMBER = NULL 
WHERE CAFE_NAME = '그린빈 카페';


